import{i as v,S as f,a as H}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&e(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const y=document.querySelector(".input-search"),x=document.getElementById("search-form"),d=document.getElementById("gallery"),u=document.querySelector(".load-more-button"),q=document.querySelector(".end-message");let l,c=1,i=[],g="";x.addEventListener("submit",async function(n){n.preventDefault(),c=1,i=[];const r=y.value.trim();r?(w(),r!==g&&(g=r,p()),await h(r,c)):v.error({title:"Error",message:"Please enter a search keyword."})});u.addEventListener("click",async function(){const n=y.value.trim();n!==g&&(l=new f('a[data-lightbox="gallery"]'),l.refresh(),p(),c++,w()),await h(n,c)});async function h(n,r){try{const s=await H.get(`https://pixabay.com/api/?key=29942317-e3405ade5aa33d4d063a2fbeb&q=${n}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`),t=s.data.totalHits/15;if(m(),s.data.hits.length>0){const o=s.data.hits;i=i.concat(o),M(i);const a=document.querySelector(".gallery a:last-child"),b=document.querySelector(".gallery a");if(a){const L=a.getBoundingClientRect(),I=b.getBoundingClientRect(),$=window.innerHeight,S=L.bottom-$-I.height*4;window.scrollBy({top:S,behavior:"smooth"})}u.style.display="block"}else u.style.display="none",q.style.display="block"}catch(s){m(),console.log(s)}}function p(){d.innerHTML=""}function w(){d.innerHTML="<p>Loading images, please wait...</p>"}function m(){d.innerHTML=""}function M(n){const r=[],s=n.map(e=>(r.push({src:e.largeImageURL,title:`Likes: ${e.likes}, Views: ${e.views}, Comments: ${e.comments}, Downloads: ${e.downloads}`}),`<a href="${e.largeImageURL}" data-lightbox="gallery" data-title="${e.tags}">
              <img src="${e.webformatURL}" alt="${e.tags}">
              <ul>
                <li>Likes:<br /> ${e.likes}</li>
                <li>Views:<br /> ${e.views}</li>
                <li>Comments:<br /> ${e.comments}</li>
                <li>Downloads:<br /> ${e.downloads}</li>
              </ul>
            </a>`)).join("");d.innerHTML+=s,l=new f('a[data-lightbox="gallery"]'),l.refresh()}
//# sourceMappingURL=commonHelpers.js.map
